services:
  weaviate:
    volumes:
      - weaviate_data:/var/lib/weaviate
    image: semitechnologies/weaviate:1.23.2
    ports:
      - 8077:8080
      - 50051:50051
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "text2vec-openai"
      ENABLE_MODULES: "text2vec-openai,generative-openai,qna-openai"

      CLUSTER_HOSTNAME: "node1"

volumes:
  weaviate_data:
